image: docker.uib.gmbh/opsi/dev/pybuilder:deb9

stages:
  - test
  - build
  - publish

pytest-macos:
  stage: test
  tags:
    - catalina-py311-x64
  script:
    - export UV_PYTHON="3.14-x86_64"
    - export UV_PYTHON_PREFERENCE="only-managed"
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_MACOS_X64}" | sh
    - uv self update
    - uv sync --frozen
    - uv run pytest --tb=short -x -o junit_family=xunit2 --junitxml=testreport_macos.xml --cov-append --cov opsi --cov-report term --cov-report xml -v tests
    - mv .coverage coverage_macos
  artifacts:
    name: "python-opsi-common_test_macos"
    paths:
      - coverage.xml
      - testreport_macos.xml
      - coverage_macos
    expire_in: 3 days

pytest-windows:
  stage: test
  tags:
    - win10-x64
  script:
    - $Env:UV_PYTHON_INSTALL_DIR = "c:\\uv\\python"
    - $Env:UV_CACHE_DIR = "c:\\uv\\cache"
    - $Env:UV_PYTHON = "3.14-x86_64"
    - $Env:UV_PYTHON_PREFERENCE = "only-managed"
    - $Env:RUSTUP_TOOLCHAIN = "stable-x86_64-pc-windows-msvc"
    - uv sync --frozen
    - uv run pytest --tb=short -x -o junit_family=xunit2 --junitxml=testreport_windows.xml --cov-append --cov opsi --cov-report term --cov-report xml -v tests
    - Rename-Item -Path .coverage -NewName coverage_windows
  artifacts:
    name: "python-opsi_test_windows"
    paths:
      - coverage.xml
      - testreport_windows.xml
      - coverage_windows
    expire_in: 3 days

test:lint-and-test:
  stage: test
  tags:
    - docker-x64
  needs:
    # We want to combine test coverage from all test jobs
    - job: pytest-macos
      artifacts: true
    - job: pytest-windows
      artifacts: true
  image: docker
  before_script:
    - TXT_HEAD="\e[46m\e[1;37m" && TXT_ERROR="\e[1;31m" && TXT_CLEAR="\e[0m"
    # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227
    - CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
    - DOCKER_COMPOSE="docker compose -f docker/python-opsi-dev/docker-compose.yml -p python-opsi-test-$CI_JOB_ID"
    - export LOCAL_WORKSPACE_DIR=$(docker inspect $CONTAINER_ID -f "{{ range .Mounts }}{{ if eq .Destination \"/builds\" }}{{ .Source }}{{end}}{{end}}")/uib/python-opsi/
    - echo $LOCAL_WORKSPACE_DIR

    - ./docker/create_env.sh

    - echo -e "${TXT_HEAD}Build docker images${TXT_CLEAR}"
    - $DOCKER_COMPOSE build --pull

    - rm -rf .venv

  after_script:
    - 'echo "CI_JOB_STATUS: $CI_JOB_STATUS"'
    - TXT_HEAD="\e[46m\e[1;37m" && TXT_ERROR="\e[1;31m" && TXT_CLEAR="\e[0m"
    - DOCKER_COMPOSE="docker compose -f docker/python-opsi-dev/docker-compose.yml -p python-opsi-test-$CI_JOB_ID"

    - '[ "$CI_DEBUG_SERVICES" = "true" ] && $DOCKER_COMPOSE logs'
    - $DOCKER_COMPOSE logs > docker.log
    - echo -e "${TXT_HEAD}Stop docker containers${TXT_CLEAR}"
    - $DOCKER_COMPOSE down -v

  script:
    - 'echo "CI_CONCURRENT_ID: $CI_CONCURRENT_ID"'
    - 'echo "CI_PROJECT_DIR: $CI_PROJECT_DIR"'

    - echo -e "${TXT_HEAD}Prepare docker containers${TXT_CLEAR}"
    - $DOCKER_COMPOSE up --remove-orphans --detach --wait --wait-timeout 120
    - $DOCKER_COMPOSE ps

    - echo -e "${TXT_HEAD}Run linters${TXT_CLEAR}"
    - $DOCKER_COMPOSE exec python-opsi-dev uv sync --frozen
    - $DOCKER_COMPOSE exec python-opsi-dev uv run ruff check opsi tests
    - $DOCKER_COMPOSE exec python-opsi-dev uv run ty check opsi tests

    - echo -e "${TXT_HEAD}Waiting for opsi-server to be ready${TXT_CLEAR}"
    - $DOCKER_COMPOSE exec python-opsi-dev bash -c 'for trynum in $(seq 1 30); do curl --silent --insecure https://opsi-server:4447 && break; sleep 6; done'
    - echo -e "${TXT_HEAD}Run pytest${TXT_CLEAR}"
    - $DOCKER_COMPOSE exec python-opsi-dev uv run pytest -x --tb=short -o junit_family=xunit2 --junitxml=testreport_linux.xml --cov-append --cov opsi --cov-report term --cov-report xml -v tests
    - $DOCKER_COMPOSE exec python-opsi-dev mv .coverage coverage_linux

    - $DOCKER_COMPOSE exec python-opsi-dev opsi-dev-cli self upgrade
    - $DOCKER_COMPOSE exec python-opsi-dev opsi-dev-cli -l info testing merge-junit-testreports testreport_*.xml testreport.xml
    - $DOCKER_COMPOSE exec python-opsi-dev opsi-dev-cli -l info testing merge-coverage-files --base-path opsi coverage_* .coverage
    - echo -e '[run]\nrelative_files = True\n' > .coveragerc
    - $DOCKER_COMPOSE exec python-opsi-dev opsi-dev-cli -l info testing coverage-report

  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
  artifacts:
    when: always
    name: 'python-opsi_test'
    paths:
      - coverage.xml
      - docker.log
    expire_in: 3 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:linux-x64:
  stage: build
  tags:
    - docker-x64
  script:
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_X64}" | sh
    - export UV_PYTHON="3.14-x86_64"
    - uv sync
    - uv run opsi-dev-cli -l debug pyinstaller build
    - mv dist/python-opsi ./python-opsi_linux_x64
    # Check if binary is working
    - ./python-opsi_linux_x64/python-opsi --version
    # Push to binaryindex
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l info binary push python-opsi_linux_x64 --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info binary push python-opsi_linux_x64'
  artifacts:
    name: 'python-opsi_linux_x64'
    paths:
      - python-opsi_linux_x64
    expire_in: 2 day

build:linux-arm64:
  stage: build
  tags:
    - docker-arm64
  script:
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_ARM64}" | sh
    - export UV_PYTHON="3.14-aarch64"
    - uv sync
    - uv run opsi-dev-cli -l debug pyinstaller build
    - mv dist/python-opsi ./python-opsi_linux_arm64
    # Check if binary is working
    - ./python-opsi_linux_arm64/python-opsi --version
    # Push to binaryindex
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-cli -l info binary push python-opsi_linux_arm64 --prerelease="$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info binary push python-opsi_linux_arm64'
  artifacts:
    name: 'python-opsi_linux_arm64'
    paths:
      - python-opsi_linux_arm64
    expire_in: 2 day

build:windows-x64:
  stage: build
  tags:
    - win10-x64
  script:
    - $Env:UV_PYTHON_INSTALL_DIR = "c:\\uv\\python"
    - $Env:UV_CACHE_DIR = "c:\\uv\\cache"
    - $Env:UV_PYTHON = "3.14-x86_64"
    - $Env:UV_PYTHON_PREFERENCE = "only-managed"
    - $Env:RUSTUP_TOOLCHAIN = "stable-x86_64-pc-windows-msvc"
    - irm "${OPSIDEVTOOLS_INSTALLER_URL_WINDOWS_X64}" | iex
    - uv run opsi-dev-cli -l debug pyinstaller build
    - opsi-dev-cli -l info signserver sign dist\python-opsi\
    - Move-Item -Path dist\python-opsi -Destination python-opsi_windows_x64
    # Check if binary is working
    - python-opsi_windows_x64\python-opsi.exe --version
    # Push to binaryindex
    - if (! $CI_COMMIT_TAG) {opsi-dev-cli -l info binary push python-opsi_windows_x64 --prerelease="$CI_JOB_ID"}
    - if ($CI_COMMIT_TAG) {opsi-dev-cli -l info binary push python-opsi_windows_x64}
  artifacts:
    name: python-opsi_windows_x64
    paths:
      - python-opsi_windows_x64

publish-uib-pypi:
  stage: publish
  script:
    - export UV_PYTHON="3.14-x86_64"
    - export UV_PYTHON_PREFERENCE="only-managed"
    - curl -sS "${OPSIDEVTOOLS_INSTALLER_URL_LINUX_X64}" | sh
    - uv self update
    - uv sync --frozen
    - uv run opsi-dev-cli -l info pypi publish --url https://pypi.uib.gmbh --overwrite
  only:
    - tags
