[project]
name = "python-opsi"
version = "4.3.23.3"
description = "python-opsi"
readme = "README.md"
requires-python = ">=3.13"
license = "AGPL-3.0-only"
dependencies = [
	"aiofiles>=25.1.0",
	"blake3>=1.0.8",
	"colorlog>=6.10.1",
	"configupdater>=3.2",
	"cryptography>=46.0.5",
	"distro>=1.9.0",
	"dnspython>=2.7.0",
	"dotenv>=0.9.9",
	"lz4>=4.4.5",
	"msgpack>=1.0; platform_system == 'Windows'",
	"hivex>=1.3; platform_system == 'Linux'",
	"msgspec>=0.19; platform_system != 'Windows'",
	"netifaces>=0.11.0",
	"packaging>=24.1,<25.0",  # TODO: LegacyVersion no longer working with packaging >= 25.0
	"psutil>=7.2.2",
	"ptyprocess>=0.7",
	"pydantic>=2.12.5",
	"pywin32>=308; platform_system == 'Windows'",
	"pywinpty>=2.0,<3.0; platform_system == 'Windows'", # pywinpty 3.0 is 64bit only
	"pyzsync>=1.0",
	"requests>=2.32.5",
	"rich>=14.3.3",
	"stamina>=25.2.0",
	"tomlkit>=0.14.0",
	"websocket-client>=1.9.0",
	"wmi>=1.5; platform_system == 'Windows'",
	"zstandard>=0.21",
	"pycryptodome>=3.23.0",
	"bcrypt>=4.0.0",
	"crypt-r>=3.13.1; platform_system == 'Linux'",
	"argon2-cffi>=25.1.0",
	"pexpect>=4.9.0; platform_system != 'Windows'",
]

[[project.authors]]
name = "uib GmbH"
email = "info@uib.de"

[[project.maintainers]]
name = "uib GmbH"
email = "info@uib.de"

[project.urls]
Homepage = "https://www.opsi.org"

[dependency-groups]
dev = [
	"hypothesis>=6.151.9",
	"pproxy>=2.7",
	"pytest-asyncio>=1.3.0",
	"pytest-coverage>=0.0",
	"pytest>=9.0",
	"ruff>=0.9",
	"ty>=0.0.18",
	"types-toml>=0.10",
	"types-aiofiles>=24.1",
	"types-netifaces>=0.11.0.20241025",
	"types-orjson>=3.6",
	"types-psutil>=6.0",
	"types-requests>=2.32",
]

[tool.uv]
extra-index-url = [ "https://pypi.uib.gmbh/simple",]
index-strategy = "unsafe-best-match"
package = true

[tool.ty.environment]
python = ".venv/bin/python"

[tool.ruff]
line-length = 140

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
follow_imports = "silent"

[tool.ruff.format]
indent-style = "tab"

[tool.pytest.ini_options]
markers = [
	"windows: mark test to run only on windows.",
	"linux: mark test to run only on linux.",
	"macos: mark test to run only on macos.",
	"posix: mark test to run only on posix.",
	"admin_permissions: mark test to run only if user has admin permissions.",
	"not_in_docker: mark test to run only if not running in docker",
	"storage_utils: mark test to run only if storage utilities are installed"
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
	"ignore::urllib3.exceptions.InsecureRequestWarning",
	"ignore:.*use of forkpty.* may lead to deadlocks in the child*:DeprecationWarning"
]


[tool.setuptools.packages.find]
include = [
	"opsi",
	"opsi.*"
]
