#! /bin/sh -e

case "$1" in
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	
	;;
    remove)
	
	;;

     purge)
     	if [ ! -z "`getent passwd pcpatch`" ]; then
		userdel pcpatch
	fi
	
	if [ ! -z "`getent group pcpatch`" ]; then
		groupdel pcpatch
	fi
	
	test -e /etc/opsi/pckeys && rm -f /etc/opsi/pckeys
	
	;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
	;;

esac

