# This file is part of the device management solution OPSI http://www.opsi.org
# Copyright (c) 2020-2026 uib GmbH <info@uib.de>
# This code is owned by the uib GmbH, Mainz, Germany (uib.de). All rights reserved.
# License: AGPL-3.0-only

from opsi.exception._exception import (
	BackendAuthenticationError,
	BackendBadValueError,
	BackendConfigurationError,
	BackendError,
	BackendIOError,
	BackendMissingDataError,
	BackendModuleDisabledError,
	BackendPermissionDeniedError,
	BackendReferentialIntegrityError,
	BackendTemporaryError,
	BackendUnableToConnectError,
	BackendUnaccomplishableError,
	OperatingSystemUnsupportedError,
	OpsiBadRpcError,
	OpsiError,
	OpsiLicenseConfigurationError,
	OpsiLicenseMissingError,
	OpsiRepositoryError,
	OpsiRpcError,
	OpsiServiceAuthenticationError,
	OpsiServiceClientCertificateError,
	OpsiServiceConnectionError,
	OpsiServiceConnectionRefusedError,
	OpsiServiceError,
	OpsiServicePermissionError,
	OpsiServiceTimeoutError,
	OpsiServiceUnavailableError,
	OpsiServiceVerificationError,
)

__all__ = [
	"BackendAuthenticationError",
	"BackendBadValueError",
	"BackendConfigurationError",
	"BackendError",
	"BackendIOError",
	"BackendMissingDataError",
	"BackendModuleDisabledError",
	"BackendPermissionDeniedError",
	"BackendReferentialIntegrityError",
	"BackendTemporaryError",
	"BackendUnableToConnectError",
	"BackendUnaccomplishableError",
	"OperatingSystemUnsupportedError",
	"OpsiBadRpcError",
	"OpsiError",
	"OpsiLicenseConfigurationError",
	"OpsiLicenseMissingError",
	"OpsiRepositoryError",
	"OpsiRpcError",
	"OpsiServiceAuthenticationError",
	"OpsiServiceClientCertificateError",
	"OpsiServiceConnectionError",
	"OpsiServiceConnectionRefusedError",
	"OpsiServiceError",
	"OpsiServicePermissionError",
	"OpsiServiceTimeoutError",
	"OpsiServiceUnavailableError",
	"OpsiServiceVerificationError",
]
